# Generated by Django 2.0.1 on 2018-02-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('internal_note', models.TextField(blank=True, default='')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('UD', 'Undefined'), ('MS', 'Mining share'), ('TX', 'Outgoing')], default='UD', max_length=2)),
                ('tx', models.CharField(blank=True, default='', max_length=200)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
            ],
        ),
    ]
