# Generated by Django 2.0.1 on 2018-02-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0003_auto_20180218_1733'),
        ('puretransaction', '0002_auto_20180218_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('error_message', models.TextField()),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
            ],
        ),
    ]
