# Generated by Django 2.0.1 on 2018-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('last_accepted_solution_at', models.DateTimeField(default=None, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
            ],
        ),
    ]
