# Generated by Django 2.0.1 on 2018-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
