# Generated by Django 2.0.1 on 2018-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_auto_20180218_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
