# Generated by Django 2.0.1 on 2018-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0003_auto_20180218_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
