# Generated by Django 2.0.1 on 2018-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0004_miner_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='ratio',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=14),
        ),
    ]
