# Generated by Django 2.0.1 on 2018-02-10 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miner', '0001_initial'),
        ('block', '0002_auto_20180204_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=20)),
                ('bible_hash', models.CharField(max_length=100, unique=True)),
                ('solution', models.TextField()),
                ('hps', models.IntegerField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('block', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=20)),
                ('bible_hash', models.CharField(max_length=100, unique=True)),
                ('solution', models.TextField()),
                ('hps', models.IntegerField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('block', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('thread_id', models.CharField(max_length=20)),
                ('hash_target', models.CharField(max_length=200)),
                ('network', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.Work'),
        ),
        migrations.AddField(
            model_name='rejectedsolution',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.Work'),
        ),
    ]
