# Generated by Django 2.0.1 on 2018-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedsolution',
            name='hps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='hps',
            field=models.IntegerField(default=0),
        ),
    ]
