# Generated by Django 2.0.1 on 2018-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_auto_20180210_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedsolution',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
