# Generated by Django 2.0.1 on 2018-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='processed',
        ),
        migrations.AddField(
            model_name='block',
            name='process_status',
            field=models.CharField(choices=[('OP', 'Open'), ('BP', 'Basics processed'), ('PS', 'Processing shares'), ('FI', 'Finished'), ('ST', 'Stale')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='block',
            name='sharedout',
            field=models.BooleanField(default=False),
        ),
    ]
